### ISSUE TITLE
OfflineBay not opening.

### ISSUE THREAD

**Issue by EggShweg** [techtacoriginal/offlinebay#2]
On download, I extracted from the .zip file (I'm on windows) and upon opening it I double-clicked the .exe file which prompted with a "Run or Cancel" screen and I clicked run, nothing happened, so I opened with Admin privileges, and still nothing.

**Comment by techtacoriginal** [comment]
Can you try to run `OfflineBay.exe` from powershell or Command prompt? It should print out an error if there's something wrong. It doesn't need admin privileges to run.

**Comment by techtacoriginal** [comment]
Closing this because of the inactivity.
