### ISSUE TITLE
Smart Search doesn't work in OSX 10.3.4

### ISSUE THREAD

**Issue by Zaithe** [techtacoriginal/offlinebay#4]
If i enable smart search the application gets stuck on searching. Enabling instant search with smart search doesn't help. I have to uncheck smart search for searching to work.

**Comment by techtacoriginal** [comment]
Hi. Can you try to run the app from terminal? It should show an error if something's wrong. You can also check the log file. It's inside your `App > Contents > Resources > app > app > data > logger.log`. Please paste the relevant errors here.

**Comment by Zaithe** [comment]
closing this as its now working.

**Comment by techtacoriginal** [comment]
@Zaithe can you explain how you fixed this issue? It seems like more people are having this same issue but unable to trace.

**Comment by Zaithe** [comment]
looks like its doing it for me again 
`2018-06-28 11:17:57.210 OfflineBay[8510:1545817] *** WARNING: Textured window <AtomNSWindow: 0x7fce7ab12da0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
Search process ended` even after it says search process ended it's still showing the searching animation.

**Comment by Zaithe** [comment]
actually going to close this again since i just read over the other issue and its pretty much exactly the same. [issue #6](https://github.com/techtacoriginal/offlinebay/issues/6)
