### ISSUE TITLE
Add seeds/peers results column and content type search filter

### ISSUE THREAD

**Issue by user135711** [techtacoriginal/offlinebay#5]
If you could add an option to asynchronously update values in a seeds peers column, then the results could be ordered by likelihood to successfully download files (I know you can double click on each one individually). Also the real site also has a content type search filter that is very useful.

**Comment by techtacoriginal** [comment]
None of those features couldn't be added because the dump file doesn't contain those data. Also it's not possible to keep scraping trackers for 3+ million torrents to update seeds/peers automatically.

**Comment by user135711** [comment]
@techtacoriginal For the seeds/peers would it be possible on the search results page to have a bulk seeds peers request for the 20 or so results displayed that gets updated asynchronously? That way you don't have to double click twenty times on each result which sounds like a job for a computer.

**Comment by techtacoriginal** [comment]
It's still not convenient to do that. It means that the application should store extra data somewhere else. Also if you check the source code, tracker scraping is a separate process so it won't break the GUI. This means a lot of scraping processes simultaneously. "Asynchronous" isn't always non-locking when a GUI is involved. Even if it was non-locking it could seriously hog the resources from renderer which will make the GUI experience hell. I can't see any scenario that this feature is convenient programmatically.
