### ISSUE TITLE
OfflineBay dump file

### ISSUE THREAD

**Issue by IoanPaleru** [techtacoriginal/offlinebay#7]
Hi. I haven't used offlinebay before, and was wondering how a new user can figure out where to download the dump file from? Thanks. Have a good day.

**Comment by techtacoriginal** [comment]
Hi @IoanPaleru, You should head over to the [Suprbay thread](https://pirates-forum.org/Thread-Release-OfflineBay-v2-Open-source-and-No-more-Java-dependency) for that information. Closing this since it's not an issue.
