### ISSUE TITLE
Doesn't run when placed in program files x86 directory (Windows 10)

### ISSUE THREAD

**Issue by r-christie** [techtacoriginal/offlinebay#9]
I downloaded the windows version of this, extracted it into my program files x86 folder then ran it. It appears to start, and I can see it in my Task manager but it hasn't done anything asides from this.

I saw in a post afew months ago another user had a similar problem (http://www.horizonhealthinc.com/Thread-Release-OfflineBay-v2-Open-source-and-No-more-Java-dependency?page=2)

Windows 10 Pro
Version	10.0.17134 Build 17134

I just copied the folder into a different directory, under c drive and ran it from there. It's maybe a windows access rights issue. I don't think you need to fix this, but perhaps just mention it in the installation hints.

**Comment by techtacoriginal** [comment]
It's not an issue. It's simply how Windows works. OfflineBay changes/modifies files from that directory hierarchy which windows doesn't allow to do without Administrator privileges. Simply run OfflineBay as administrator and see if it works.

**Comment by r-christie** [comment]
I also tried running with administrator but it still seemed to not do too much, but as you say it's not too much an issue if you choose an installation directory outside of program files.

**Comment by techtacoriginal** [comment]
Agreed. Using a general location would be much simpler. Closing the issue.
